### ISSUE TITLE
Merge in latest WhisperSystems to TextSecure

### ISSUE THREAD

**Issue by chriswil-codev** [ForstaLabs/TextSecure-Server#2]
Merge in the code from the latest whisper systems for Signal Server.

**Comment by mayfield** [comment]
We're basically a hard fork.  I don't expect us to ever take an update from WhisperSystems.  What's driving this @chriswil-codev?

**Comment by chriswil-codev** [comment]
Sync’ing the latest.  Fixes/updates.  Is this bad?

**Comment by chriswil-codev** [comment]
From the looks of it, we haven't made much changes to the original branch when it was forked.  Until we come to a point where we make significant modifications wouldn't it be a good thing to catch up on any fixes/updates?  It was brought up on discussion with Jeff/Jen as I was being tasked with Java work.  I wouldn't mind sitting down with you and going over the architecture and configuration of how we're using WhisperSystems.  For one, a current priority would be to start building deployment silos for Dev/Stage/Prod so we could test things like main-fork updates.

**Comment by mayfield** [comment]
Only if it doesn't affect our clients which are essentially locked in the
past.  Unless there's stuff we want it's probably more pain than it's worth.
